### PR TITLE
French translation + Adding http://markdotto.github.com/github-buttons/

### PR DESCRIPTION
**Pull request by jena-s-lab**

### CODE REVIEW

**Comment by zenorocha** [comment]
Cool!!!

**Comment by zenorocha** [comment]
It's now online!

https://twitter.com/#!/jqbp/status/146734859975532545

**Comment by zenorocha** [comment]
But I remove those Github buttons, did not like it =/

**Comment by jena-s-lab** [comment]
agreed, i did it only because you asked. Originals remain the bests.

**Pull request merged**
